version: '3'
services:
  database:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
